Repository zimmerman-team/IATI.cloud.frontend, pull requests merged in 2020-05, with the labels that each got.

#124 DEV-372
  .circleci/config.yml
Labels: size/S

#126 DS-2233
  public/data/humanitarianScopeVocab.json
  src/app/modules/QueryBuilder/fragments/additional-filters/consts.tsx
  src/app/modules/QueryBuilder/state/effects.ts
  src/app/modules/QueryBuilder/state/store.ts
  src/app/state/interfaces/HumanitarianScopeVocabInterface.ts
  src/app/state/models/ApplicationStoreModel.ts
  src/app/state/services/api-service.ts
  src/app/state/store/index.ts
Labels: size/M

#127 DS-2137
  src/app/modules/QueryBuilder/fragments/results/layout.tsx
Labels: size/S

#128 DS-2241
  src/app/modules/QueryBuilder/state/effects.ts
Labels: size/S

#123 #2229
  src/app/components/surfaces/Background/index.tsx
Labels: size/XS

#125 2230
  src/app/modules/QueryBuilder/fragments/additional-filters/layout.tsx
  src/app/modules/QueryBuilder/fragments/core-filters/index.tsx
Labels: size/M

#129 develop to master
  .circleci/config.yml
  public/data/humanitarianScopeVocab.json
  src/app/components/surfaces/Background/index.tsx
  src/app/modules/QueryBuilder/fragments/additional-filters/consts.tsx
  src/app/modules/QueryBuilder/fragments/results/layout.tsx
  src/app/modules/QueryBuilder/state/effects.ts
  src/app/modules/QueryBuilder/state/store.ts
  src/app/state/interfaces/HumanitarianScopeVocabInterface.ts
  src/app/state/models/ApplicationStoreModel.ts
  src/app/state/services/api-service.ts
  src/app/state/store/index.ts
Labels: size/L

#115 #2169
  package.json
  public/mitm.html
  public/sw.js
  src/app/modules/QueryBuilder/fragments/results/common/DownloadButton/index.tsx
  src/app/modules/QueryBuilder/fragments/results/layout.tsx
  src/app/modules/QueryBuilder/fragments/results/util.ts
  src/app/utils/streamsaver/index.js
Labels: size/XL

#130 Revert "#2169"
  package.json
  public/mitm.html
  public/sw.js
  src/app/modules/QueryBuilder/fragments/results/common/DownloadButton/index.tsx
  src/app/modules/QueryBuilder/fragments/results/layout.tsx
  src/app/modules/QueryBuilder/fragments/results/util.ts
  src/app/utils/streamsaver/index.js
Labels: size/XL

#131 DEV-374
  .circleci/config.yml
Labels: size/S

#132 Feature/2169
  package.json
  public/mitm.html
  public/sw.js
  src/app/components/datadisplay/DataTable/common/nodatacellcomp.tsx
  src/app/components/datadisplay/DataTable/index.tsx
  src/app/modules/QueryBuilder/fragments/results/common/DownloadButton/index.tsx
  src/app/modules/QueryBuilder/fragments/results/layout.tsx
  src/app/modules/QueryBuilder/fragments/results/util.ts
  src/app/utils/streamsaver/index.js
Labels: size/XL

#133 DS-2247
  src/app/modules/QueryBuilder/state/effects.ts
Labels: size/XS

#134 Fix transaction url for transaction-recipient-country filter
  .circleci/config.yml
  package.json
  public/mitm.html
  public/sw.js
  src/app/components/datadisplay/DataTable/common/nodatacellcomp.tsx
  src/app/components/datadisplay/DataTable/index.tsx
  src/app/modules/QueryBuilder/fragments/results/common/DownloadButton/index.tsx
  src/app/modules/QueryBuilder/fragments/results/layout.tsx
  src/app/modules/QueryBuilder/fragments/results/util.ts
  src/app/modules/QueryBuilder/state/effects.ts
  src/app/utils/streamsaver/index.js
Labels: size/XL

#135 DS-2252
  src/app/modules/QueryBuilder/state/effects.ts
Labels: size/XS

#136 update
  src/app/modules/QueryBuilder/state/effects.ts
Labels: size/XS
