Repository zimmerman-team/IATI.cloud.frontend, pull requests merged in 2020-03, with the labels that each got.

#110 feat: enabled banner
  .zeplin/components.json
  src/app/components/feedback/Banners/BannerNotice.tsx
  src/app/index.tsx
Labels: size/S

#112 DS-1845
  src/app/components/inputs/selects/AsyncSelect/index.tsx
Labels: size/XS

#113 #2133
  package.json
  src/app/components/inputs/selects/ConnectedSelect/common/index.tsx
  src/app/components/inputs/textinputs/IconTextInputFIeld/index.tsx
  src/app/components/inputs/textinputs/SearchInputField/index.tsx
  src/app/components/inputs/textinputs/SearchInputField/styles.ts
  src/app/modules/QueryBuilder/fragments/additional-filters/layout.tsx
  src/app/modules/QueryBuilder/state/effects.ts
  src/index.css
  yarn.lock
Labels: size/L

#116 DS-2166
  public/data/humanitarianScope.json
  src/app/modules/QueryBuilder/fragments/additional-filters/consts.tsx
  src/app/modules/QueryBuilder/state/effects.ts
  src/app/modules/QueryBuilder/state/store.ts
  src/app/state/interfaces/HumanitarianScopeInterface.ts
  src/app/state/models/ApplicationStoreModel.ts
  src/app/state/services/api-service.ts
  src/app/state/store/index.ts
Labels: size/M
