Repository zimmerman-team/IATI.cloud.frontend, pull requests merged in 2020-06, with the labels that each got.

#137 DS-2278
  src/app/state/models/QueryModel.ts
Labels: size/XS

#141 feat: redirect to querybuilder
  package.json
  src/app/modules/QueryBuilder/layout.tsx
  yarn.lock
Labels: size/M

#140 align querybuilder tabs with design
  .babelrc
  .circleci/config.yml
  .eslintrc.js
  .stylelintrc
  .vscode/settings.json
  craco.config.js
  package.json
  src/app/modules/About/layout.tsx
  src/app/modules/QueryBuilder/common/NavigationButton.tsx
  src/app/modules/QueryBuilder/layout.tsx
  yarn.lock
Labels: size/XL

#146 DS-2291
  src/app/modules/QueryBuilder/fragments/core-filters/index.tsx
Labels: size/XS

#148 #2232: updated vd for documentation
  package.json
  src/app/modules/Documentation/common/DocDetail/common/ApiBaseList/index.tsx
  src/app/modules/Documentation/common/DocDetail/common/ApiBaseList/model.ts
  src/app/modules/Documentation/common/DocDetail/common/ApiCallFragment/index.tsx
  src/app/modules/Documentation/common/DocDetail/common/ui/SubCaregoryDescription.tsx
  src/app/modules/Documentation/common/DocDetail/common/ui/SubCategoryFragment.tsx
  src/app/modules/Documentation/common/DocDetail/common/ui/SubCategoryHeader.tsx
  src/app/modules/Documentation/common/DocDetail/common/utils/ui/index.tsx
  src/app/modules/Documentation/common/DocDetail/index.tsx
  src/app/modules/Documentation/common/DocLanding/index.tsx
  src/app/modules/Documentation/common/DocSideBar/common/TreeItem.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/ApiDocSearchBoxContainer.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/ApiDocSearchInput.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/CustomLink.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/CustomLink2.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/SubItemContainer.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/SubLink1.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/SubLink2.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/SubLink3.tsx
  src/app/modules/Documentation/common/DocSideBar/index.tsx
  yarn.lock
Labels: size/XXL

#145 Remove iati.cloud references #2264
  CODE_OF_CONDUCT.md
  README.md
  src/app/components/inputs/selects/AsyncSelect/index.tsx
  src/app/components/inputs/textinputs/ChipInputField/index.tsx
  src/app/components/surfaces/Footer/index.tsx
  src/app/modules/Documentation/state/model.ts
  src/app/modules/Documentation/state/service.ts
  src/app/modules/Landing/common/LandingMidSection.tsx
  src/app/modules/QueryBuilder/fragments/results/layout.tsx
  src/app/state/api/index.ts
Labels: size/L
