Repository zimmerman-team/IATI.cloud.frontend, pull requests merged in 2020-08, with the labels that each got.

#201 feat: linked IATI logo in footer
  src/app/components/surfaces/Footer/index.tsx
  yarn.lock
Labels: size/L

#203 style: titles in query builder are black
  src/app/components/common/FieldInputLabel/index.tsx
  src/app/components/inputs/selects/ConnectedSelect/common/index.tsx
  src/app/modules/querybuilder-module/fragments/core-filters/index.tsx
  src/app/modules/querybuilder-module/fragments/core-filters/model.ts
Labels: size/S

#208 #204
  src/app/components/datadisplay/DataTable/index.tsx
Labels: size/XS

#210 feat: added done button to qb results page
  src/app/modules/querybuilder-module/fragments/results/layout.tsx
Labels: size/XS

#211 removed text from API docs
  src/app/modules/documentation-module/common/DocLanding/index.tsx
Labels: size/XS

#207 test: added visual regression to all tests
  .happo.js
  cypress/integration/about.spec.ts
  cypress/integration/apiDocSearch.spec.ts
  cypress/integration/home.spec.ts
  cypress/integration/qbAdditionalFilters.spec.ts
  cypress/integration/qbCoreFilters.spec.ts
  cypress/integration/qbOutputFormat.spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  package.json
  yarn.lock
Labels: size/L

#212 feat: paging to results table
  src/app/components/datadisplay/DataTable/index.tsx
Labels: size/M

#213 feat: choose sample size in results section
  src/app/components/inputs/radiobuttons/RadioButtonGroup/common/RadioGroupTitle/index.tsx
  src/app/modules/querybuilder-module/fragments/results/layout.tsx
  src/app/state/api/index.ts
  src/app/state/models/QueryModel.ts
  src/app/state/store/index.ts
Labels: size/L

#214 chore: simplify method complexity
  src/app/components/datadisplay/Lists/ListControls/index.tsx
Labels: size/S

#216 2403
  .circleci/config.yml
  src/app/modules/documentation-module/common/DocSideBar/common/TreeItem.tsx
  src/app/modules/documentation-module/common/DocSideBar/common/ui/SubLink3.tsx
  src/app/modules/documentation-module/common/DocSideBar/utils.ts
  src/app/state/models/QueryModel.ts
Labels: size/M

#217 DEV-401: Fix permission denied
  .circleci/config.yml
Labels: size/M

#218 2406 - 2398 - Footer changes
  src/app/Routes.tsx
  src/app/components/inputs/buttons/AppBarButton/index.tsx
  src/app/components/surfaces/AppBar/index.tsx
  src/app/components/surfaces/Footer/FooterLG.tsx
  src/app/components/surfaces/Footer/FooterMD.tsx
  src/app/components/surfaces/Footer/FooterSM.tsx
  src/app/components/surfaces/Footer/index.tsx
Labels: size/XL
