Repository zimmerman-team/IATI.cloud.frontend, pull requests merged in 2020-07, with the labels that each got.

#180 chore: changed text
  src/app/modules/About/layout.tsx
Labels: size/XS

#179 Minor adjustments of documentation page to design
  src/app/modules/Documentation/common/DocLanding/index.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/CategoryContainer.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/DocsideBarContainer.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/DocsideBarNavList.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/LicenseFooter.tsx
  src/app/modules/Documentation/common/DocSideBar/index.tsx
Labels: size/M

#161 2283
  package.json
  src/app/modules/QueryBuilder/common/NavigationButton.tsx
  src/app/modules/QueryBuilder/fragments/output-format/model.ts
  src/app/modules/QueryBuilder/fragments/results/layout.tsx
  src/app/modules/QueryBuilder/state/effects.ts
  src/app/modules/QueryBuilder/state/utils.ts
  src/app/state/api/index.ts
  yarn.lock
Labels: size/XXL

#187 style: license is now sticky in API page
  src/app/modules/Documentation/common/DocSideBar/common/ui/DocsideBarContainer.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/LicenseFooter.tsx
  src/app/modules/Documentation/common/DocSideBar/index.tsx
Labels: size/M

#189 fix: docs page
  src/app/modules/About/layout.tsx
  src/app/modules/Documentation/common/DocLanding/index.tsx
  src/app/modules/Documentation/common/DocSideBar/common/ui/SubLink1.tsx
  src/app/modules/Documentation/common/DocSideBar/index.tsx
Labels: size/M

#191 fix: added padding to navbuttons
  src/app/modules/QueryBuilder/common/StepNavigatorContainer.tsx
  src/app/modules/QueryBuilder/layout.tsx
  yarn.lock
Labels: size/L

#193 Fix: all cypress tests work again
  cypress/integration/apiDocNavigation.spec.ts
  cypress/integration/apiDocSearch.spec.ts
  cypress/integration/qbAdditionalFilters.spec.ts
  cypress/integration/qbCoreFilters.spec.ts
  cypress/integration/qbOutputFormat.spec.ts
  cypress/integration/qbResults.spec.ts
  cypress/support/index.js
Labels: size/L

#195 feat: search bar is now insensitive to case #194
  src/app/modules/Documentation/common/DocSideBar/utils.ts
Labels: size/S

#197 DS-2323
  src/app/modules/QueryBuilder/state/effects.ts
Labels: size/XS
