Repository zimmerman-team/IATI.cloud.frontend, pull requests merged in 2021-02, with the labels that each got.

#241 chore: change cookie key and remove 'reparse in progress' text
  src/app/components/feedback/Banners/CovidBanner/index.tsx
Labels: size/S

#235 2501
  src/app/components/datadisplay/DataTable/index.tsx
  src/app/modules/querybuilder-module/fragments/additional-filters/consts.tsx
  src/app/modules/querybuilder-module/state/effects.ts
  src/app/modules/querybuilder-module/state/utils/getAidTypeCodes.ts
  src/app/modules/querybuilder-module/state/utils/getCountries.ts
  src/app/modules/querybuilder-module/state/utils/getDefaultCurrency.ts
  src/app/modules/querybuilder-module/state/utils/getDefaultFinanceType.ts
  src/app/modules/querybuilder-module/state/utils/getDefaultFlowType.ts
  src/app/modules/querybuilder-module/state/utils/getDefaultTiedStatus.ts
  src/app/modules/querybuilder-module/state/utils/getGeneralSearch.ts
  src/app/modules/querybuilder-module/state/utils/getHumanitarian.ts
  src/app/modules/querybuilder-module/state/utils/getParticipatingOrgs.ts
  src/app/modules/querybuilder-module/state/utils/getRegions.ts
  src/app/modules/querybuilder-module/state/utils/getReportingOrgTypes.ts
  src/app/modules/querybuilder-module/state/utils/getSectorVocabs.ts
  src/app/modules/querybuilder-module/state/utils/getSectors.ts
Labels: size/XL

#239 feat: change title to no longer contain its duplicate title field
  src/app/modules/querybuilder-module/state/effects.ts
Labels: size/XS

#242 Release
  src/app/components/HomeHeader/index.tsx
  src/app/components/datadisplay/DataTable/index.tsx
  src/app/components/feedback/Banners/CovidBanner/index.tsx
  src/app/components/surfaces/AppBar/index.tsx
  src/app/components/surfaces/Header/index.tsx
  src/app/index.tsx
  src/app/modules/querybuilder-module/fragments/additional-filters/consts.tsx
  src/app/modules/querybuilder-module/state/effects.ts
  src/app/modules/querybuilder-module/state/utils/getAidTypeCodes.ts
  src/app/modules/querybuilder-module/state/utils/getCountries.ts
  src/app/modules/querybuilder-module/state/utils/getDefaultCurrency.ts
  src/app/modules/querybuilder-module/state/utils/getDefaultFinanceType.ts
  src/app/modules/querybuilder-module/state/utils/getDefaultFlowType.ts
  src/app/modules/querybuilder-module/state/utils/getDefaultTiedStatus.ts
  src/app/modules/querybuilder-module/state/utils/getGeneralSearch.ts
  src/app/modules/querybuilder-module/state/utils/getHumanitarian.ts
  src/app/modules/querybuilder-module/state/utils/getParticipatingOrgs.ts
  src/app/modules/querybuilder-module/state/utils/getRegions.ts
  src/app/modules/querybuilder-module/state/utils/getReportingOrgTypes.ts
  src/app/modules/querybuilder-module/state/utils/getSectorVocabs.ts
  src/app/modules/querybuilder-module/state/utils/getSectors.ts
Labels: size/XL
