Repository zimmerman-team/IATI.cloud.frontend, pull requests merged in 2021-07, with the labels that each got.

#259 making changes to reflect IATI.cloud instead of IATI Datastore
  cypress/integration/about.spec.ts
  cypress/integration/home.spec.ts
  public/data/docs.json
  public/index.html
  src/app/components/datadisplay/DataTable/index.tsx
  src/app/components/feedback/Banners/BannerNotice.tsx
  src/app/components/feedback/Banners/CovidBanner/index.tsx
  src/app/components/surfaces/Cards/ArticleCard/mock.ts
  src/app/modules/about-module/index.tsx
  src/app/modules/about-module/layout.tsx
  src/app/modules/documentation-module/index.tsx
Labels: size/M

#263 Chore/small updates
  README.md
  src/app/modules/about-module/layout.tsx
  src/app/modules/documentation-module/state/model.ts
  src/app/modules/documentation-module/state/service.ts
  src/app/modules/querybuilder-module/fragments/results/layout.tsx
Labels: size/M

#261 Variety of copy & URL/I changes
  .circleci/config.yml
  README.md
  public/index.html
  src/app/components/feedback/Banners/CovidBanner/index.tsx
  src/app/components/inputs/selects/AsyncSelect/index.tsx
  src/app/components/surfaces/Footer/FooterLG.tsx
  src/app/components/surfaces/Footer/FooterMD.tsx
  src/app/components/surfaces/Footer/FooterSM.tsx
  src/app/modules/about-module/layout.tsx
  src/app/modules/common/ModuleHeader/index.tsx
  src/app/modules/documentation-module/common/DocDetail/common/ApiCallFragment/index.tsx
  src/app/modules/documentation-module/common/DocDetail/common/DocCallPreview/common/RequestExample/code.ts
  src/app/modules/documentation-module/common/DocDetail/common/DocCallPreview/common/RequestExample/index.tsx
  src/app/modules/documentation-module/common/DocDetail/common/DocCallPreview/common/RequestResponse/index.tsx
  src/app/modules/documentation-module/state/model.ts
  src/app/modules/documentation-module/state/service.ts
  src/app/modules/landing-module/common/LandingMidSection.tsx
  src/app/modules/landing-module/index.tsx
  src/app/modules/landing-module/layout.tsx
  src/app/modules/notfound-module/index.tsx
  src/app/modules/notfound-module/layout.tsx
  src/app/modules/querybuilder-module/fragments/results/layout.tsx
  src/app/modules/querybuilder-module/index.tsx
  src/app/modules/querybuilder-module/layout.tsx
  src/app/state/api/index.ts
Labels: size/L

#264 Some more minor changes
  public/index.html
Labels: size/S

#265 IATI-2639: Loading indicator for documentation
  src/app/modules/documentation-module/common/DocLanding/common/ui/LoadingIndicator.tsx
  src/app/modules/documentation-module/common/DocLanding/index.tsx
Labels: size/M
